import { existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

/**
 * Locate the committed golden fixtures by walking up from this file until a
 * golden directory is found. This avoids a fragile fixed relative depth and
 * resolves two different layouts:
 *   - source tree: the fixtures live at `<repo>/python/tests/golden` — they are
 *     generated by the Python impl and shared as the cross-impl contract.
 *   - Docker image: the `typescript/` layer is collapsed into `/app` and the
 *     fixtures are copied to `/app/tests/golden`, so the depth differs.
 * At each level we try both `python/tests/golden` and `tests/golden`.
 */
export function goldenDir(): string {
  let dir = path.dirname(fileURLToPath(import.meta.url));
  const suffixes = [
    ["python", "tests", "golden"],
    ["tests", "golden"],
  ];
  for (let i = 0; i < 8; i++) {
    for (const suffix of suffixes) {
      const candidate = path.join(dir, ...suffix);
      if (existsSync(candidate)) return candidate;
    }
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  throw new Error("could not locate golden fixtures (python/tests/golden or tests/golden)");
}
